#!/usr/bin/env bash

# Update the package index to ensure we install the latest versions of packages
apt-get update
apt-get install -y nginx

# This ensures Nginx listens on port 80
sed -i 's/^\(.*listen.*\)80/\180/' /etc/nginx/sites-available/default

# Restart the Nginx service to apply the configuration changes
service nginx restart

# Create a simple HTML file in the default web root directory (/var/www/html)
echo "Hello World!" > /var/www/html/index.html
